mongodb:
  enabled: true
  uri: mongodb+srv://your-username:your-password@your-cluster.mongodb.net
  database: your-database

supabase:
  enabled: true
  url: postgresql://postgres.jvyokyxdxzuxologgljm@aws-0-eu-central-1.pooler.supabase.com:6543/postgres
  db_password: "[YOUR-PASSWORD]"
  keep_records_limit: 100  # number of records to keep in keep_alive_reserved table 