name: Service Keeper

on:
  schedule:
    - cron: '0 3 * * *'  # Run at 3:00 UTC daily (5:00 CEST, 22:00 EST previous day)
  workflow_dispatch:        # Allow manual trigger
  push:
    branches: [ main ]      # Run on push to main branch
    paths-ignore:           # Don't run on these files
      - '**.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    
    - name: Build
      run: |
        go build -v -o keeper ./cmd/keeper
        
    - name: Generate config from secrets
      run: |
        cat > config.yaml << EOF
        # Global identifier for this keeper instance
        hostname: "github-action-keeper"

        mongodb:
          enabled: true
          uri: ${{ secrets.MONGODB_URI }}
          database: ${{ secrets.MONGODB_DATABASE }}
          keep_records_limit: 100

        supabase:
          enabled: true
          uri: ${{ secrets.SUPABASE_URI }}
          keep_records_limit: 100

        cloudamqp:
          enabled: true
          uri: ${{ secrets.CLOUDAMQP_URI }}
          queue: ${{ secrets.CLOUDAMQP_QUEUE }}
        EOF
      
    - name: Run keeper
      run: ./keeper
      
    - name: Clean up config
      if: always()
      run: rm -f config.yaml 